# Generated by Django 5.1.4 on 2026-08-28 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backseat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatbotDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=260)),
                ('content_type', models.CharField(max_length=120)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chatbot_documents', to='backseat.userprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatbotDocumentChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('position', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='backseat.chatbotdocument')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='ChatbotUnknownQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('normalized_text', models.TextField()),
                ('fallback_answer', models.TextField(blank=True)),
                ('status', models.CharField(default='NEW', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chatbot_unknown_questions', to='backseat.userprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='chatbotdocument',
            index=models.Index(fields=['created_at'], name='backseat_ch_created_602b1e_idx'),
        ),
        migrations.AddIndex(
            model_name='chatbotdocumentchunk',
            index=models.Index(fields=['document'], name='backseat_ch_documen_df4991_idx'),
        ),
        migrations.AddIndex(
            model_name='chatbotunknownquestion',
            index=models.Index(fields=['status'], name='backseat_ch_status_61db9c_idx'),
        ),
        migrations.AddIndex(
            model_name='chatbotunknownquestion',
            index=models.Index(fields=['created_at'], name='backseat_ch_created_8e824d_idx'),
        ),
    ]
