from django.contrib import admin
from django.urls import path
from backseat import views

urlpatterns = [
    path("django-admin/", admin.site.urls),
    path("", views.home, name="home"),
    path("about", views.static_page, {"slug": "about"}, name="about"),
    path("how-it-works", views.static_page, {"slug": "how-it-works"}, name="how_it_works"),
    path("safety", views.static_page, {"slug": "safety"}, name="safety"),
    path("community-guidelines", views.static_page, {"slug": "community-guidelines"}, name="community_guidelines"),
    path("terms", views.static_page, {"slug": "terms"}, name="terms"),
    path("privacy", views.static_page, {"slug": "privacy"}, name="privacy"),
    path("disclaimers", views.static_page, {"slug": "disclaimers"}, name="disclaimers"),
    path("become-a-rider", views.static_page, {"slug": "become-a-rider"}, name="become_a_rider"),
    path("register", views.register_view, name="register"), path("login", views.login_view, name="login"), path("logout", views.logout_view, name="logout"),
    path("find-a-ride", views.find_a_ride, name="find_a_ride"), path("offer-a-ride", views.offer_a_ride, name="offer_a_ride"), path("rides/<int:ride_id>", views.ride_detail, name="ride_detail"), path("rider/<int:rider_id>", views.rider_profile, name="rider_profile"),
    path("donate/<str:code>", views.donate, name="donate"), path("donate/receipt/<int:donation_id>", views.receipt, name="receipt"), path("qr/<str:code>.png", views.qr_png, name="qr_png"), path("top-contributors", views.impact, name="top_contributors"), path("charity-impact", views.impact, name="charity_impact"),
    path("dashboard", views.dashboard, name="dashboard"), path("dashboard/my-rides", views.dashboard_section, {"section": "My Rides"}, name="my_rides"), path("dashboard/my-trips", views.dashboard_section, {"section": "My Trips"}, name="my_trips"), path("dashboard/donations", views.dashboard_section, {"section": "Donations"}, name="donations"), path("dashboard/payments", views.dashboard_section, {"section": "Payments"}, name="payments"), path("dashboard/impact", views.dashboard_section, {"section": "Impact"}, name="dashboard_impact"), path("dashboard/profile", views.profile, name="profile"), path("dashboard/qr", views.dashboard_qr, name="dashboard_qr"),
    path("rides/<int:ride_id>/status", views.update_ride, name="update_ride"), path("joins/<int:join_id>/status", views.update_join, name="update_join"), path("joins/<int:join_id>/message", views.send_join_message, name="send_join_message"), path("rider/sharing", views.toggle_sharing, name="toggle_sharing"), path("reports/<int:user_id>", views.report_user, name="report_user"), path("blocks/<int:user_id>", views.block_user, name="block_user"),
    path("admin", views.admin_console, name="admin_console"), path("admin/users", views.admin_console, name="admin_users"), path("admin/riders", views.admin_console, name="admin_riders"), path("admin/rides", views.admin_console, name="admin_rides"), path("admin/donations", views.admin_console, name="admin_donations"), path("admin/reports", views.admin_console, name="admin_reports"), path("admin/verification", views.admin_console, name="admin_verification"), path("admin/fraud", views.admin_console, name="admin_fraud"), path("admin/leaderboard", views.admin_console, name="admin_leaderboard"), path("admin/audit-log", views.admin_console, name="admin_audit_log"), path("admin/charities", views.admin_console, name="admin_charities"),
    path("admin/action/<str:kind>/<int:item_id>", views.admin_action, name="admin_action"),
    path("api/auth/register", views.api_register, name="api_register"),
    path("api/auth/login", views.api_login, name="api_login"),
    path("api/auth/logout", views.api_logout, name="api_logout"),
    path("api/auth/me", views.api_me, name="api_me"),
    path("api/profile", views.api_profile, name="api_profile"),
    path("api/rider/onboard", views.api_rider_onboard, name="api_rider_onboard"),
    path("api/rider/vehicle", views.api_rider_vehicle, name="api_rider_vehicle"),
    path("api/rider/sharing", views.api_rider_sharing, name="api_rider_sharing"),
    path("api/rider/qr/regenerate", views.api_rider_qr_regenerate, name="api_rider_qr_regenerate"),
    path("api/rides", views.api_rides, name="api_rides"),
    path("api/rides/<int:ride_id>", views.api_ride_detail, name="api_ride_detail"),
    path("api/rides/<int:ride_id>/join", views.api_ride_join, name="api_ride_join"),
    path("api/rides/<int:ride_id>/joins/<int:join_id>", views.api_join_detail, name="api_join_detail"),
    path("api/rides/<int:ride_id>/joins/<int:join_id>/messages", views.api_join_messages, name="api_join_messages"),
    path("api/donate/initiate", views.api_donate_initiate, name="api_donate_initiate"),
    path("api/donate/confirm", views.api_donate_confirm, name="api_donate_confirm"),
    path("api/notifications", views.api_notifications, name="api_notifications"),
    path("api/notifications/read-all", views.api_notifications_read_all, name="api_notifications_read_all"),
    path("api/notifications/<int:notification_id>", views.api_notification_read, name="api_notification_read"),
    path("api/reports", views.api_reports, name="api_reports"),
    path("api/blocks", views.api_blocks, name="api_blocks"),
    path("api/sos", views.api_sos, name="api_sos"),
    path("api/chatbot", views.api_chatbot, name="api_chatbot"),
    path("api/admin/chatbot-documents", views.api_admin_chatbot_documents, name="api_admin_chatbot_documents"),
    path("admin/chatbot-documents", views.admin_chatbot_documents, name="admin_chatbot_documents"),
    path("api/admin/users/<int:item_id>", views.api_admin_update, {"kind": "user"}, name="api_admin_users"),
    path("api/admin/riders/<int:item_id>", views.api_admin_update, {"kind": "rider"}, name="api_admin_riders"),
    path("api/admin/rides/<int:item_id>", views.api_admin_update, {"kind": "ride"}, name="api_admin_rides"),
    path("api/admin/donations/<int:item_id>", views.api_admin_update, {"kind": "donation"}, name="api_admin_donations"),
    path("api/admin/reports/<int:item_id>", views.api_admin_update, {"kind": "report"}, name="api_admin_reports"),
    path("api/admin/charities/<int:item_id>", views.api_admin_update, {"kind": "charity"}, name="api_admin_charities"),
    path("api/admin/campaigns/<int:item_id>", views.api_admin_update, {"kind": "campaign"}, name="api_admin_campaigns"),
]
